steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/fuzzy-chainsaw:1-$COMMIT_SHA', '-f=Dockerfile-1', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/fuzzy-chainsaw:2-$COMMIT_SHA', '-t', 'gcr.io/$PROJECT_ID/fuzzy-chainsaw:2', '-f=Dockerfile-2', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/fuzzy-chainsaw:3-$COMMIT_SHA', '-f=Dockerfile-3', '.']

images: ['gcr.io/$PROJECT_ID/fuzzy-chainsaw:1-$COMMIT_SHA',
         'gcr.io/$PROJECT_ID/fuzzy-chainsaw:2-$COMMIT_SHA',
         'gcr.io/$PROJECT_ID/fuzzy-chainsaw:3-$COMMIT_SHA',
         'gcr.io/$PROJECT_ID/fuzzy-chainsaw:2',
         ]
