steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/fuzzy-chainsaw:1-$COMMIT_SHA', '-f=Dockerfile-1', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/fuzzy-chainsaw:2-$COMMIT_SHA', '-f=Dockerfile-2', '.']

- name: 'gcr.io/cloud-builders/docker'
  args: ['tag', 'gcr.io/$PROJECT_ID/fuzzy-chainsaw:1-$COMMIT_SHA', 'gcr.io/$PROJECT_ID/fuzzy-chainsaw:1']
- name: 'gcr.io/cloud-builders/docker'
  args: ['tag', 'gcr.io/$PROJECT_ID/fuzzy-chainsaw:2-$COMMIT_SHA', 'gcr.io/$PROJECT_ID/fuzzy-chainsaw:2']


images: ['gcr.io/$PROJECT_ID/fuzzy-chainsaw:1-$COMMIT_SHA',
         'gcr.io/$PROJECT_ID/fuzzy-chainsaw:2-$COMMIT_SHA',
         'gcr.io/$PROJECT_ID/fuzzy-chainsaw:1',
         'gcr.io/$PROJECT_ID/fuzzy-chainsaw:2',
         ]
